### ISSUE TITLE
No module named ecdsa despite everything installed

### ISSUE THREAD

**Issue by kyleboddy** [achow101/payment-proto-interface#3]
Running `python tui.py`, I get:

> Traceback (most recent call last):
>   File "tui.py", line 5, in <module>
>     import util
>   File "/root/payment-proto-interface/util.py", line 35, in <module>
>     import ecdsa
> ImportError: No module named ecdsa

But `easy_install ecdsa` yields:

> Searching for ecdsa
> Best match: ecdsa 0.13
> Processing ecdsa-0.13-py3.5.egg
> ecdsa 0.13 is already the active version in easy-install.pth
> 
> Using /usr/local/lib/python3.5/dist-packages/ecdsa-0.13-py3.5.egg
> Processing dependencies for ecdsa
> Finished processing dependencies for ecdsa

`pip install ecdsa` yields:

> Requirement already satisfied: ecdsa in /usr/local/lib/python3.5/dist-packages/ecdsa-0.13-py3.5.egg

Any ideas?

**Comment by kyleboddy** [comment]
I manually cloned electrum and ran its `setup.py` and that seemed to work. Shrug.

https://github.com/spesmilo/electrum

**Comment by achow101** [comment]
Did you run the `setup.py` provided in this repo?

**Comment by GGGunrunner** [comment]
Same thing..

apt-get install python3-pip - OK
pip3 install pyqt5 - OK
python3 setup.py install - OK 

(Processing ecdsa-0.13-py3.6.egg
ecdsa 0.13 is already the active version in easy-install.pth)

python tui.py
Traceback (most recent call last):
  File "tui.py", line 5, in <module>
    import util
  File "/root/payment-proto-interface/util.py", line 35, in <module>
    import ecdsa
ImportError: No module named ecdsa


.....

Do you guys *ever* check on a clean machine? Or you have some 500+ dependencies installed, and if it runs on *your* setup - you just rush to release it?

**Comment by GGGunrunner** [comment]
Same thing..

apt-get install python3-pip - OK
pip3 install pyqt5 - OK
python3 setup.py install - OK 

(Processing ecdsa-0.13-py3.6.egg
ecdsa 0.13 is already the active version in easy-install.pth)

python tui.py
Traceback (most recent call last):
  File "tui.py", line 5, in <module>
    import util
  File "/root/payment-proto-interface/util.py", line 35, in <module>
    import ecdsa
ImportError: No module named ecdsa


.....

Do you guys *ever* check on a clean machine? Or you have some 500+ dependencies installed, and if it runs on *your* setup - you just rush to release it?

**Comment by GGGunrunner** [comment]
Same thing..

apt-get install python3-pip - OK
pip3 install pyqt5 - OK
python3 setup.py install - OK 

(Processing ecdsa-0.13-py3.6.egg
ecdsa 0.13 is already the active version in easy-install.pth)

python tui.py
Traceback (most recent call last):
  File "tui.py", line 5, in <module>
    import util
  File "/root/payment-proto-interface/util.py", line 35, in <module>
    import ecdsa
ImportError: No module named ecdsa


.....

Do you guys *ever* check on a clean machine? Or you have some 500+ dependencies installed, and if it runs on *your* setup - you just rush to release it?

**Comment by achow101** [comment]
> Do you guys ever check on a clean machine? Or you have some 500+ dependencies installed, and if it runs on your setup - you just rush to release it?

It was tested in a clean virtualenv.

***

Note that I won't help you if you just come here and spam, accuse, and be condescending towards me. This is a personal (i.e. one man, just mine) project and I have no obligation to help you.

**Comment by lf94** [comment]
For what it's worth, I am having the same issue. Maybe it's because I've run it with sudo?...

On debian stretch. Going to try using electrum's as suggested.

The issue appears to be `python <command>`, because `python` is a link to `python2`.

When installing everything with `pip3` it works no problem. Thanks for the script @achow101 !
